openapi: 3.0.0
info:
  description: Storage API for persisting individual server health readings and player telemetry events
  version: "1.0.0"
  title: Game Server Storage API
  contact:
    email: cbell86@my.bcit.ca

paths:
  /events/server-health:
    post:
      summary: Persist a single server health reading
      operationId: app.report_server_health_reading
      description: Receives ONE server health reading (batch + reading fields) and stores it in the database
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ServerHealthReading'
      responses:
        '201':
          description: reading successfully stored
        '400':
          description: invalid input, object is invalid

  /events/player-telemetry:
    post:
      summary: Persist a single player telemetry event
      operationId: app.report_player_telemetry_event
      description: Receives ONE player telemetry event (batch + event fields) and stores it in the database
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/PlayerTelemetryEvent'
      responses:
        '201':
          description: event successfully stored
        '400':
          description: invalid input, object is invalid

components:
  schemas:
    ServerHealthReading:
      type: object
      required:
        - server_id
        - sent_timestamp
        - batch_id
        - server_region
        - active_players
        - cpu_usage
        - ram_usage
        - recorded_timestamp
      properties:
        # common (from batch)
        server_id:
          type: string
          format: uuid
          description: ID of the server/device sending this data
          example: "dc0a7a50-2795-43e3-b6c5-28b69aab1b5e"
        sent_timestamp:
          type: string
          format: date-time
          description: Date/time the batch was sent by the sender
          example: "2026-01-08T22:15:30Z"
        batch_id:
          type: string
          format: uuid
          description: Unique id for the batch request this reading came from
          example: "2c11dd14-dd4e-492c-a697-f39b6dbb2426"
        server_region:
          type: string
          description: Region/cluster where the sender lives
          example: "ca-west-1"

        # reading-specific
        server_location:
          type: string
          description: Optional human-readable location
          example: "Vancouver"
        active_players:
          type: integer
          description: Number of active players at moment of reading
          example: 231
        cpu_usage:
          type: number
          example: 87.9
        ram_usage:
          type: number
          example: 54.1
        recorded_timestamp:
          type: string
          format: date-time
          description: Date/time this reading was recorded on the server
          example: "2026-01-08T22:15:30Z"

    PlayerTelemetryEvent:
      type: object
      required:
        - server_id
        - sent_timestamp
        - batch_id
        - player_id
        - event_timestamp
        - player_ping
      properties:
        # common (from batch)
        server_id:
          type: string
          format: uuid
          example: "dc0a7a50-2795-43e3-b6c5-28b69aab1b5e"
        sent_timestamp:
          type: string
          format: date-time
          example: "2026-01-08T22:16:10Z"
        batch_id:
          type: string
          format: uuid
          description: Unique id for the batch request this event came from
          example: "a12f0c99-0a6c-4c55-b2a9-5f3a5c6a90d1"
        server_region:
          type: string
          description: Region/cluster where the sender lives (optional for telemetry based on your original YAML)
          example: "ca-west-1"

        # event-specific
        player_id:
          type: string
          format: uuid
          example: "2c11dd14-dd4e-492c-a697-f39b6dbb2426"
        event_timestamp:
          type: string
          format: date-time
          example: "2026-01-08T22:16:01Z"
        player_ping:
          type: integer
          description: player ping in milliseconds
          example: 41
        player_level:
          type: integer
          nullable: true
          example: 99
        action:
          type: string
          nullable: true
          description: type of action/event
          enum: [login, logout, kill, death, level_up, chat_message]
          example: "level_up"
